package com.theflash.hpw.bookshare;

public class countrydata {
    public static final String countrynames[]={"Afghanistan", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda",
            "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan","Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus",
            "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory",
            "Brunei", "Bulgaria" , "Burkina Faso" , "Burundi","Cambodia", "Cameroon" , "Canada" , "Cape Verde" , "Cayman Islands" , "Central African Republic" ,
            "Chad " , "Chile" , "China" , "Christmas Island" , "Cocos  Islands" , "Colombia" , "Comoros" , "Congo, Democratic(Former Zaire)" ,
            "Congo" , "Cook Islands" ,"Costa Rica" , "Cote D'Ivoire" , "Croatia" , "Cuba " , "Cyprus " , "Czech Republic" , "Czechoslavakia","Denmark",
            "Djibouti" , "Dominica" , "Dominican Republic","East Timor" + "Ecuador" , "Egypt" , "El Salvador", "Equatorial Guinea" , "Eritrea " , "Estonia" ,
            "Ethiopia","Falkland Islands" , "Faroe Islands" , "Fiji" , "Finland" , "France" , "French Guiana" , "French Polynesia" , "French Southern Territories",
            "Gabon " , "Gambia" , "Georgia" , "Germany" , "Ghana" , "Gibraltar" ,
            "Great Britain(United Kingdom)" ,
            "Greece" ,
            "Greenland" ,
            "Grenada" ,
            "Guadeloupe" ,
            "Guam" ,
            "Guatemala" ,
            "Guinea" ,
            "Guinea-Bissau" ,
            "Guyana",
            "Haiti" ,
            "Heard Island" ,
            "Holy See" ,
            "Honduras" ,
            "Hong Kong",
            "Hungary" ,
            "Iceland" ,
            "India" ,
            "Indonesia",
            "Iran" ,
            "Iraq" ,
            "Ireland",
            "Israel" ,
            "Italy" ,
            "Jamaica" ,
            "Japan" ,
            "Jordan" ,
            "Kazakstan" ,
            "Kenya" ,
            "Kiribati" ,
            "Korea" ,
            "South Korea" ,
            "Kuwait" ,
            "Kyrgyzstan" ,
            "Lao People's Democratic Republic" ,
            "Latvia" ,
            "Lebanon" ,
            "Lesotho" ,
            "Liberia" ,
            "Libya" ,
            "Liechtenstein" ,
            "Lithuania" ,
            "Luxembourg " ,
            "Macau " ,
            "Macedonia" ,
            "Madagascar" ,
            "Malawi" ,
            "Malaysia" ,
            "Maldives" ,
            "Mali" ,
            "Malta" ,
            "Marshall Islands" ,
            "Martinique" ,
            "Mauritania" ,
            "Mauritius " ,
            "Mayotte " ,
            "Mexico" ,
            "Micronesia" ,
            "Moldova" ,
            "Monaco" ,
            "Mongolia" ,
            "Montserrat" ,
            "Morocco" ,
            "Mozambique" ,
            "Myanmar" ,
            "Namibia" ,
            "Nauru" ,
            "Nepal" ,
            "Netherlands" ,
            "Netherlands Antilles" ,
            "New Caledonia" ,
            "New Zealand" ,
            "Nicaragua",
            "Niger" ,
            "Nigeria" ,
            "Niue" ,
            "Norfolk Island" ,
            "Northern Mariana Islands" ,
            "Norway" ,
            "Oman" ,
            "Pakistan" ,
            "Palau" ,
            "Palestinian State" ,
            "Panama" ,
            "Papua New Guinea" ,
            "Paraguay" ,
            "Peru" ,
            "Philippines" ,
            "Pitcairn Island",
            "Poland" ,
            "Portugal" ,
            "Puerto Rico" ,
            "Qatar" ,
            "Reunion" ,
            "Romania" ,
            "Russia" ,
            "Russian Federation " ,
            "Rwanda" ,
            "Saint Helena" ,
            "Saint Kitts and Nevis",
            "Saint Lucia " ,
            "Saint Pierre and Miquelon" ,
            "Saint Vincent and the Grenadines " ,
            "Samoa" ,
            "San Marino" ,
            "Sao Tome and Principe" ,
            "Saudi Arabia" ,
            "Serbia, Republic" ,
            "Senegal" ,
            "Seychelles" ,
            "Sierra Leone" ,
            "Singapore" ,
            "Slovakia" ,
            "Slovenia" ,
            "Solomon Islands" ,
            "Somalia" ,
            "South Africa",
            "South Georgia",
            "Spain" ,
            "Sri Lanka",
            "Sudan" ,
            "Suriname" ,
            "Svalbard" ,
            "Swaziland" ,
            "Sweden" ,
            "Switzerland" ,
            "Syria" ,
            "Taiwan" ,
            "Tajikistan" ,
            "Tanzania" ,
            "Thailand" ,
            "Togo" ,
            "Tokelau" ,
            "Tonga" ,
            "Trinidad and Tobago" ,
            "Tromelin Island" ,
            "Tunisia" ,
            "Turkey" ,
            "Turkmenistan" ,
            "Turks and Caicos Islands" ,
            "Tuvalu" ,
            "Uganda" ,
            "Ukraine" ,
            "United Arab Emirates",
            "United Kingdom" ,
            "United States" ,
            "United States Minor Outlying Islands" ,
            "Uruguay" ,
            "Uzbekistan" ,
            "Vanuatu " ,
            "Vatican City State" ,
            "Venezuel" ,
            "Vietnam" ,
            "Virgin Islands, British" ,
            "Virgin Islands, United States" ,
            "Wallis and Futuna Islands" ,
            "Western Sahara (Former Spanish Sahara)" ,
            "Yemen" ,
            "Yugoslavia" ,
            "Zaire" ,
            "Zambia" ,
            "Zimbabwe"

    };
    public static final String countryareacode[]={"+93", "+355", "+213", "+1-684", "+376", "+244", "+1-264", "+672", "+1-268", "+54",
            "+374", "+297", "+61", "+43", "+994","+1-242", "+973" , "+880" , "+1-246" , "+375" , "+32" , "+501" , "+229" , "+1-441" , "+975" ,
            "+591" , "+387" , "+267" , "" , "+55" , "" , "+673" , "+359" , "+226" , "+257","+855", "+237" , "+1" , "+238" , "+1-345" , "+236" ,
            "+235" , "+56" , "+86" , "+53" , "+61" , "+57" , "+269" , "+243" , "+242" , "+682" , "+506" , "+225" , "+385" , "+53" , "+357" , "+420" ,
            "","+45" , "+253" , "+1-767" , "+1-809","+670" , "+593 " , "+20" , "+503" , "+240" , "+291" , "+372" , "+251","+500" , "+298" ,
            "+679" , "+358" , "+33" , "+594" , "+689" , "","+241" ,
            "+220" ,
            "+995" ,
            "+49" ,
            "+233" ,
            "+350" ,
            "" ,
            "+30",
            "+299",
            "+1-473",
            "+590" ,
            "+1-671",
            "+502" ,
            "+224" ,
            "+245" ,
            "+592",
            "+509" ,
            "" ,
            "" ,
            "+504",
            "+852" ,
            "+36",
            "+354",
            "+91" ,
            "+62" ,
            "+98" ,
            "+964" ,
            "+353" ,
            "+972" ,
            "+39",
            "+1-876",
            "+81" ,
            "+962",
            "+7" ,
            "+254",
            "+686" ,
            "+850" ,
            "+82" ,
            "+965" ,
            "+996",
            "+856" ,
            "+371" ,
            "+961" ,
            "+266" ,
            "+231" ,
            "+218" ,
            "+423" ,
            "+370" ,
            "+352",
            "+853" ,
            "+389" ,
            "+261" ,
            "+265" ,
            "+60" ,
            "+960" ,
            "+223" ,
            "+356" ,
            "+692" ,
            "+596" ,
            "+222",
            "+230",
            "+269",
            "+52",
            "+691",
            "+373",
            "+377",
            "+976",
            "+1-664",
            "+212",
            "+258",
            "+95",
            "+264",
            "+674",
            "+977",
            "+31",
            "+599",
            "+687",
            "+64",
            "+505",
            "+227",
            "+234",
            "+683",
            "+672",
            "+1-670",
            "+47",
            "+968",
            "+92",
            "+680",
            "+970",
            "+507",
            "+675",
            "+595",
            "+51",
            "+63",
            "",
            "+48",
            "+351",
            "+1-787",
            "+974 ",
            "+262",
            "+40",
            "",
            "+7",
            "+250",
            "+290",
            "+1-869",
            "+1-758",
            "+508",
            "+1-784",
            "+685",
            "+378",
            "+239",
            "+966",
            "",
            "+221",
            "+248",
            "+232",
            "+65",
            "+421",
            "+386",
            "+677",
            "+252",
            "+27",
            "",
            "+34",
            "+94",
            "+249",
            "+597",
            "",
            "+268",
            "+46",
            "+41",
            "+963",
            "+886",
            "+992",
            "+255",
            "+66",
            "",
            "+690",
            "+676",
            "+1-868",
            "",
            "+216",
            "+90",
            "+993",
            "+1-649",
            "+688",
            "+256",
            "+380",
            "+971",
            "+44",
            "+1",
            "",
            "+598",
            "+998",
            "+678",
            "+418",
            "+58",
            "+84",
            "+1-284",
            "+1-340",
            "+681",
            "",
            "+967",
            "",
            "",
            "+260",
            "+263",


    };
}
